apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: project-api
build:
  artifacts:
    - image: project-api
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - .k8s/deployment.yml
    - .k8s/service.yml
    - .k8s/ingress.yml
